# Metadata for your course

title: Lab Starter
tagline: test
description: test description

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     lab-starter-template
  repo:     lab-starter-template


# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Title of the issue
  body: issue_1.md
  comments:
    - issue_1.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Step 1
  description: description
  event: issues
  actions:
  - type: createIssue
    title: Title of the issue
    body: issue_1.md
    comments:
      - issue_1.md

- title: Step 2
  description: description 2
  event: issues
  actions:
  - type: createIssue
    title: Title of the issue 2
    body: issue_1.md
    comments:
      - issue_1.md
