# Metadata for your course

title: Lab Starter
tagline: test
description: test description

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     lab-starter-template
  repo:     lab-starter-template


# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Title of the issue
  body: issue-body.md
  comments:
    - issue-comment.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title:          # the title of the step, shown to the learner in the course progress page
  description:    # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  event:          # a list of the actions that will occur when the step is triggered by an event
  actions:
  - type: createIssue
    title: Title of the issue
    body: issue-body.md
    comments:
      - issue-comment.md
